#!/bin/sh

file="$XDG_DATA_HOME/bookmarks"

bookmark=$(:|dmenu -p "edit bookmark:")
if [ -z "$bookmark" ]
then
    notify-send -e "bookmark creation cancelled."
    return 1
else
    bookmarkUrl="${bookmark%% *}"
    if grep -q "^$bookmarkUrl" "$file"
    then
	notify-send -e "already bookmarked."
    else
	notify-send -e "bookmark successfully added as $bookmark."
	echo "$bookmark" >> "$file"
    fi
fi
