#!/bin/sh

# Let us first choose an editor
eds="\
emacs\temacsclient -c -a emacs
nvim\tst nvim"

choice="$(echo "$eds" | cut -f 1 | dmenu -p "Choose editor:")" || exit 1

DMEDITOR=$(echo "$eds" | grep "^$choice" | cut -f2-)

# And let us then choose a config file to edit
cmds="\
zshrc\t$DMEDITOR $HOME/dotfiles/zsh/.zshrc
profile\t$DMEDITOR $HOME/dotfiles/profile/profile
doom config\t$DMEDITOR $HOME/dotfiles/doom/config.el
doom packages\t$DMEDITOR $HOME/dotfiles/doom/packages.el
doom init\t$DMEDITOR $HOME/dotfiles/doom/init.el
nvim\t$DMEDITOR $HOME/dotfiles/nvim/init.vim
dwm\t$DMEDITOR $HOME/Git/suckless/dwm/config.h
dwm autostart\t$DMEDITOR $HOME/.local/share/dwm/autostart.sh
dwm blocks\t$DMEDITOR $HOME/Git/suckless/dwmblocks/blocks.h
st\t$DMEDITOR $HOME/Git/suckless/st/config.h
dmenu\t$DMEDITOR $HOME/Git/suckless/dmenu/config.h
dmenu config\t$DMEDITOR $HOME/dotfiles/scripts/dmenuconfig
slstatusbar\t$DMEDITOR $HOME/Git/suckless/dmenu/config.h
pacman\tsudo $DMEDITOR /etc/pacman.conf
picom\t$DMEDITOR $HOME/dotfiles/picom/picom.conf
newsboat config\t$DMEDITOR $HOME/dotfiles/newsboat/config
newsboat urls\t$DMEDITOR $HOME/dotfiles/newsboat/urls
mbsync config\t$DMEDITOR $HOME/.config/isync/mbsyncrc"

choice="$(echo "$cmds" | cut -f 1 | dmenu -l 20 -p "Edit config of:")" || exit 1

`echo "$cmds" | grep "^$choice" | cut -f2-`
