#!/bin/sh

# Let us first choose an editor
eds="\
emacs\temacsclient -c -a emacs
nvim\tst nvim"

choice="$(echo "$eds" | cut -f 1 | dmenu -p "Choose editor:")" || exit 1

DMEDITOR=$(echo "$eds" | grep "^$choice" | cut -f2-)

# And let us then choose a config file to edit
cmds="\
bibliography\t$DMEDITOR $HOME/Tools/Zotero/bibtex/library.bib 
bookmarks\t$DMEDITOR $HOME/.local/share/bookmarks
dmenu config\t$DMEDITOR $HOME/dotfiles/scripts/dmenuconfig
dmenu\t$DMEDITOR $HOME/Git/suckless/dmenu/config.h
dwm autostart\t$DMEDITOR $HOME/.local/share/dwm/autostart.sh
dwm blocks\t$DMEDITOR $HOME/Git/suckless/dwmblocks/blocks.h
dwm\t$DMEDITOR $HOME/Git/suckless/dwm/config.h
mbsync config\t$DMEDITOR $HOME/.config/isync/mbsyncrc
newsboat config\t$DMEDITOR $HOME/dotfiles/newsboat/config
newsboat urls\t$DMEDITOR $HOME/dotfiles/newsboat/urls
nvim\t$DMEDITOR $HOME/dotfiles/nvim/init.vim
pacman\tsudo $DMEDITOR /etc/pacman.conf
picom\t$DMEDITOR $HOME/dotfiles/picom/picom.conf
profile\t$DMEDITOR $HOME/dotfiles/profile/profile
slstatusbar\t$DMEDITOR $HOME/Git/suckless/dmenu/config.h
st\t$DMEDITOR $HOME/Git/suckless/st/config.h
zshrc\t$DMEDITOR $HOME/dotfiles/zsh/.zshrc"

choice="$(echo "$cmds" | cut -f 1 | dmenu -l 20 -p "Edit config of:")" || exit 1

`echo "$cmds" | grep "^$choice" | cut -f2-`
