#!/bin/sh
file="${XDG_DATA_HOME:-$HOME/.local/share}/bookmarks"

sel="$(grep -v '^#' "$file" | dmenu -l 20 -F)"
[ -z "$sel" ] && exit 0

# print the last tab-separated field (the URL)
url="$(printf '%s' "$sel" | awk -F ' - ' '{print $NF}')"
[ -z "$url" ] && exit 1


xdotool type --clearmodifiers --delay 0 -- "$(printf '%s' "$url")"
