#!/bin/sh

# This script is called on startup to remap keys.

# Increase key speed via a rate change
xset r rate 300 50
# Map the caps lock key to super
setxkbmap -option caps:super -variant altgr-intl
# But when it is pressed only once, treat it as escape
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
# Set keypad behaviour to mac default
setxkbmap -option numpad:mac
# And set numpad to something useful, such as insert
xmodmap -e "keysym 0xff7f = Insert"

