#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
        4) pamixer --allow-boost -i 1;;
        5) pamixer --allow-boost -d 1;;

esac

[ $(pamixer --get-mute) = true ] && echo  && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=" "
elif [ "$vol" -lt "30" ]; then
	icon=" "
else
	icon=" "
fi

echo "$icon $vol%"
